version: '3'
services:
  # mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jinang123
      MYSQL_DATABASE: gkube
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # es
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # 项目本身
  gkube:
    restart: always
    build:
      context: . # 指定Dockerfile文件所在路径
      dockerfile: Dockerfile # 指定Dockerfile文件名称
    image: gkube:v1
    container_name: gkube
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/opt/config/config.yaml
volumes:
  mysql_data:
  es_data: